# Generated by Django 3.1.7 on 2023-05-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='total price'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(verbose_name='price'),
        ),
    ]
